### ISSUE TITLE
Query error on using client.team fetch method

### ISSUE THREAD

**Issue by aga5tya** [linear/linear#160]
I'm seeing the below error but was working as expected before. Not sure if I'm missing something here.

```
UnhandledPromiseRejectionWarning: Error: Cannot query field "defaultTemplateForMembersId" on type "Team". Did you mean "defaultTemplateForMembers" or "defaultTemplateForNonMembers"?
at q (/Users/aga5tya/Sites/linear-changelog-generator/node_modules/@linear/sdk/dist/index-cjs.min.js:16:5568)
    at /Users/aga5tya/Sites/linear-changelog-generator/node_modules/@linear/sdk/dist/index-cjs.min.js:17:603899
```

Code reference:

```js
import SDK from '@linear/sdk'

const { LinearClient } = SDK

const linearClient = new LinearClient({
    apiKey: process.env.LINEAR_TOKEN,
})
const team = await linearClient.team("<*OurTeamID*>")

```

Updated to the latest package, but still seem to have the error.

**Comment by lbertenasco** [comment]
experiencing same error, fixed by removing `defaultTemplateForNonMembersId` field  from `TeamFragmentDoc`.

**Comment by tommoor** [comment]
The underlying issue was addressed, sorry for the disruption
