### ISSUE TITLE
Malformed repo names produces a misleading error

### ISSUE THREAD

**Issue by grahamc** [linear/linear#187]
Assume an organization named `foo` which owns a repository named `bar`.

Entering a malformed repo name like `bar`, instead of the full `foo/bar` like this:

```
? From which repo do you want to import issues from (e.g. "facebook/react") bar
```

produces an infinite stream of the following error:

```
Error: Unable to find repo bar/undefined. Did you select `repo` scope for your GitHub token?
    at GithubImporter.<anonymous> (/nix/store/y9r60ar88lwq6a21q0ff7qnvl4ch0gb2-linear-import/share/importer/dist/cli.js:409:31)
    at Generator.next (<anonymous>)
    at fulfilled (/nix/store/y9r60ar88lwq6a21q0ff7qnvl4ch0gb2-linear-import/share/importer/dist/cli.js:69:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I did grant the `repo` scope. It strikes me that the import tool could detect that the string I entered was parsed as the org name and that the repo name is undefined, and produce a nicer error.

**Comment by pacocoursey** [comment]
Hey, this seems like a valid bug but I'm curious why you'd enter just `bar` when the example text clearly shows the `<org>/<repo>` format? (`facebook/react`)

**Comment by sahilsobhani** [comment]
Hey! Just opened a PR for this — let me know if anything should be updated or improved. It auto-fixes #187 @grahamc @pacocoursey
