### ISSUE TITLE
Error importing csv

### ISSUE THREAD

**Issue by 8enmann** [linear/linear#274]
Getting the following stack trace

```
? Select your exported CSV file of Linear issues kanban.csv
TypeError: Cannot read properties of undefined (reading 'split')
    at LinearCsvImporter.<anonymous> (/Users/ben/.npm/_npx/e539fa3db1efc4a4/node_modules/@linear/import/dist/cli.js:524:41)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/ben/.npm/_npx/e539fa3db1efc4a4/node_modules/@linear/import/dist/cli.js:69:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Tried node v16 and v18
```bash
❯ nvm use stable
Now using node v18.13.0 (npm v8.19.3)
```

**Comment by 8enmann** [comment]
Resolved by removing non-matching columns. Better error message would be nice :)

**Comment by guillaumelachaud** [comment]
Hi!

I've filed an issue for us to improve the error messages. Let me know if you still face any problem with your import!

**Comment by peteruithoven** [comment]
@guillaumelachaud can you maybe reference that issue? 

I'm facing the same issue:
```
? Which service would you like to import from? Linear (CSV export)
? Select your exported CSV file of Linear issues data/linear_import.csv
TypeError: Cannot read properties of undefined (reading 'split')
    at LinearCsvImporter.<anonymous> (/home/peteruithoven/.volta/tools/image/packages/@linear/import/lib/node_modules/@linear/import/dist/cli.js:1187:41)
    at Generator.next (<anonymous>)
    at fulfilled (/home/peteruithoven/.volta/tools/image/packages/@linear/import/lib/node_modules/@linear/import/dist/cli.js:72:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
