### ISSUE TITLE
Failed Trello Import - Reserved Label Name

### ISSUE THREAD

**Issue by Keshavdulal** [linear/linear#348]
Hi,
I am trying to import a relatively chunky JSON(2.6kb) from a Trello board that we have been using for over a year now.

We used Labels on Trello.
Something like this frequently among the tickets.
![image](https://github.com/linear/linear/assets/16687310/651b60e7-a80b-4b8f-99d3-2abb12dd5b68)

When I try to import the Json with fields such as `labels`, `labelNames`, `idLabels`, I get the following error.
Tried with latest cli-importer on node v16.17.0 and v18.13.0

Any help is appreciated to make this import happen.
Happy to share the JSON file Privately w/ maintainers if reqd. 
Ping me at keshav@sessami.co for the file.

Thanks.

Import Error:
```
linear-import
? Input your Linear API key (https://linear.app/settings/api) <API KEY>
? Which service would you like to import from? Trello (JSON export)
? Select your exported JSON file of Trello cards trello-sessami-exp.json
? Would you like to discard the archived cards? Yes
? Would you like to discard the (possibly unarchived) cards within archived lists? Yes
? Do you want to create a new team for imported issues? No
? Import into team: [SES] Sessami
? Do you want to import to a specific project? Yes
? Import into project: WebApp
? Do you want to include comments in the issue description? Yes
? Do you want to assign these issues to yourself? Yes
D [Error]: Reserved label name - The label name is reserved.
    at j (/Users/keshavdulal/.nvm/versions/node/v16.17.0/lib/node_modules/@linear/import/node_modules/@linear/sdk/dist/index-cjs.min.js:1:5850)
    at /Users/keshavdulal/.nvm/versions/node/v16.17.0/lib/node_modules/@linear/import/node_modules/@linear/sdk/dist/index-cjs.min.js:1:1118534
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'InvalidInput',
  errors: [
    y {
      type: 'InvalidInput',
      userError: true,
      path: [Array],
      message: 'The label name is reserved.'
    }
  ],
  query: 'mutation createIssueLabel($input: IssueLabelCreateInput!, $replaceTeamLabels: Boolean) {\n' +
    '  issueLabelCreate(input: $input, replaceTeamLabels: $replaceTeamLabels) {\n' +
    '    ...IssueLabelPayload\n' +
    '  }\n' +
    '}\n' +
    '\n' +
    'fragment IssueLabelPayload on IssueLabelPayload {\n' +
    '  __typename\n' +
    '  lastSyncId\n' +
    '  issueLabel {\n' +
    '    id\n' +
    '  }\n' +
    '  success\n' +
    '}\n',
  variables: {
    input: {
      name: 'Priority',
      description: undefined,
      color: '#C52828',
      teamId: '8d6bb47f-0897-4ee1-94e5-89269edae96f'
    }
  },
  status: 200,
  data: null,
  raw: ia [Error]: reserved label name: {"response":{"errors":[{"message":"reserved label name","path":["issueLabelCreate"],"locations":[{"line":2,"column":3}],"extensions":{"code":"INPUT_ERROR","type":"invalid input","userError":true,"userPresentableMessage":"The label name is reserved.","meta":{}}}],"data":null,"status":200,"headers":{}},"request":{"query":"mutation createIssueLabel($input: IssueLabelCreateInput!, $replaceTeamLabels: Boolean) {\n  issueLabelCreate(input: $input, replaceTeamLabels: $replaceTeamLabels) {\n    ...IssueLabelPayload\n  }\n}\n\nfragment IssueLabelPayload on IssueLabelPayload {\n  __typename\n  lastSyncId\n  issueLabel {\n    id\n  }\n  success\n}\n","variables":{"input":{"name":"Priority","color":"#C52828","teamId":"8d6bb47f-0897-4ee1-94e5-89269edae96f"}}}}
      at aa.<anonymous> (/Users/keshavdulal/.nvm/versions/node/v16.17.0/lib/node_modules/@linear/import/node_modules/@linear/sdk/dist/index-cjs.min.js:1:330928)
      at Generator.next (<anonymous>)
      at l (/Users/keshavdulal/.nvm/versions/node/v16.17.0/lib/node_modules/@linear/import/node_modules/@linear/sdk/dist/index-cjs.min.js:1:720)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    response: {
      errors: [Array],
      data: null,
      status: 200,
      headers: [ri [Headers]]
    },
    request: {
      query: 'mutation createIssueLabel($input: IssueLabelCreateInput!, $replaceTeamLabels: Boolean) {\n' +
        '  issueLabelCreate(input: $input, replaceTeamLabels: $replaceTeamLabels) {\n' +
        '    ...IssueLabelPayload\n' +
        '  }\n' +
        '}\n' +
        '\n' +
        'fragment IssueLabelPayload on IssueLabelPayload {\n' +
        '  __typename\n' +
        '  lastSyncId\n' +
        '  issueLabel {\n' +
        '    id\n' +
        '  }\n' +
        '  success\n' +
        '}\n',
      variables: [Object]
    }
  }
}
```

**Comment by guillaumelachaud** [comment]
Hi @Keshavdulal 

There are a couple of issue labels that are reserved and not allowed on the platform:

```
    "assignee"
    "cycle"
    "effort"
    "estimate"
    "hours"
    "priority"
    "project"
    "state"
    "status"
```

If your import contains a label with any of these names, it will fail. The easiest solution would be for you to rename the label in Trello, export to JSON again and then import again in CLI. 

If that's not possible, you could try to edit the CLI importer to add code that would override label names on the fly before the import, by renaming them to something that's not restricted.

**Comment by Keshavdulal** [comment]
Hi @guillaumelachaud, 

I thank you immensely for helping me fix the issue. ❤️
I was able to import 316 tickets from Trello and now my team to start using linear smoothly!

In my case following two labels were causing problems in so renamed them to something else on vscode.
```
  "state"
  "status"
```

Have a nice day!
