### ISSUE TITLE
Can't fetch teams

### ISSUE THREAD

**Issue by thomaspaulmann** [linear/linear#38]
Whenever I try to fetch teams, I get some server internal errors. Here is my script:

```
const linearClient = new LinearClient({
  apiKey: process.env.LINEAR_API_TOKEN
})

async function getTeams() {
  const teams = await linearClient.teams()
  console.log(teams)
}

getTeams()
```

And this is the error I'm getting:
```
(node:46256) UnhandledPromiseRejectionWarning: Error: An internal server error has occurred.
    at dn (/Users/.../linear-script/node_modules/@linear/sdk/dist/index-cjs.min.js:7:18444)
    at /Users/.../linear-script/node_modules/@linear/sdk/dist/index-cjs.min.js:22:14434
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:46256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:46256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When catching the exception, I get a long error description which hints that something is wrong with the query. The same query works in GarphiQL if that helps debugging.

Am I doing something wrong?

**Comment by jorilallo** [comment]
@thomaspaulmann this was an internal mismatch on types. I pushed a fix and it should be available in few minutes time after which the request should work.

**Comment by thomaspaulmann** [comment]
Thanks for the quick fix @jorilallo, gonna check it out tomorrow. It’s getting late here in London :-P
