### ISSUE TITLE
Bug: issue.history API fails when node IssueHistory.actors is null

### ISSUE THREAD

**Issue by ishmam-mahmud** [linear/linear#556]
**Current behaviour**:

The following code using @linear/sdk@22.0.0:
```TypeScript
const linearClient = _internals.LinearClient({
  apiKey: 'api key here',
}); // 

const issueId = 'issue id here';
const issue = await linearClient.issue(issueId);
console.log('issue', issue); # works fine

const issueHistoryConnection = await issue.history(); # this line throws
# these lines never run
console.log('after');
console.log('issueHistoryConnection', issueHistoryConnection);
const issueHistory = issueHistoryConnection.nodes;
```

throws the following error:
```
TypeError: Cannot read properties of null (reading 'map')
    at new cs (https://esm.sh/v135/@linear/sdk@24.0.0/denonext/sdk.mjs:29:1225336)
    at https://esm.sh/v135/@linear/sdk@24.0.0/denonext/sdk.mjs:29:1229315
    at Array.map (<anonymous>)
    at new In (https://esm.sh/v135/@linear/sdk@24.0.0/denonext/sdk.mjs:29:1229308)
    at Oc.<anonymous> (https://esm.sh/v135/@linear/sdk@24.0.0/denonext/sdk.mjs:29:1394941)
    at Generator.next (<anonymous>)
    at m (https://esm.sh/v135/@linear/sdk@24.0.0/denonext/sdk.mjs:7:826)
    at eventLoopTick (ext:core/01_core.js:64:7)
```

I am running on
```
deno 1.40.3 (release, x86_64-unknown-linux-gnu)
v8 12.1.285.6
typescript 5.3.3
```

I inspected the minified code at https://esm.sh/v135/@linear/sdk@24.0.0/denonext/sdk.mjs:29:1225336 and found a `i.actors.map` without a `?` in between, and I used the linear graphql explorer to verify that `IssueHistory.actors` is null when this error is thrown.

Please let me know if there is any extra information I can provide to help debug this.

**Comment by tommoor** [comment]
This issue has been addressed in `@linear/sdk@25.0.0`
