### ISSUE TITLE
"UserId is required" on client.teams()

### ISSUE THREAD

**Issue by KuhlTime** [linear/linear#566]
I get the following error when using the `.teams()` method. I am using `bun v1.1.13` but I also tested this with `node v20.12.2`. Furthermore, I have tested other requests, and it is just the `.teams()` and `.team(teamId)` request that do not work for me.

```
error: UserId is required. - userId is required.
 errors: [
  {
    "type": "InvalidInput",
    "userError": true,
    "path": [
      "teams",
      "nodes",
      0,
      "membership"
    ],
    "message": "userId is required."
  }
]

      at new b (/Users/kuhltime/dev/emmy/notion-to-linear/node_modules/@linear/sdk/dist/index-cjs.min.js:1:2939)
      at new D (/Users/kuhltime/dev/emmy/notion-to-linear/node_modules/@linear/sdk/dist/index-cjs.min.js:1:3785)
      at O (/Users/kuhltime/dev/emmy/notion-to-linear/node_modules/@linear/sdk/dist/index-cjs.min.js:1:5902)
      at /Users/kuhltime/dev/emmy/notion-to-linear/node_modules/@linear/sdk/dist/index-cjs.min.js:1:1478758
1 | "use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("stream"),i=require("http"),n=require("url"),a=require("https"),t=require("zlib"),d=require("crypto");function l(e){return e&&"object"==typeof e&&"default"in e?e:{default:e}}var m,o=l(e),r=l(i),s=l(n),u=l(a),k=l(t),p=l(d);function c(e,i){var n={};for(var a in e)Object.prototype.hasOwnProperty.call(e,a)&&i.indexOf(a)<0&&(n[a]=e[a]);if(null!=e&&"function"==typeof Object.getOwnPropertySymbols){var t=0;for(a=Object.getOwnPropertySymbols(e);t<a.length;t++)i.indexOf(a[t])<0&&Object.prototype.propertyIsEnumerable.call(e,a[t])&&(n[a[t]]=e[a[t]])}return n}function v(e,i,n,a){return new(n||(n=Promise))((function(t,d){function l(e){try{o(a.next(e))}catch(e){d(e)}}function m(e){try{o(a.throw(e))}catch(e){d(e)}}function o(e){var i;e.done?t(e.value):(i=e.value,i instanceof n?i:new n((function(e){e(i)}))).then(l,m)}o((a=a.apply(e,i||[])).next())}))}function N(e){return null!=e}"function"==typeof SuppressedError&&SuppressedError,exports.LinearE | ... truncated
```

my code is very simple and looks like this:

```typescript
import { LinearClient } from '@linear/sdk'

const client = new LinearClient({
  apiKey: process.env.LINEAR_TOKEN
})

const teams = await client.teams()

console.dir(teams, { depth: null })
```

**Comment by KuhlTime** [comment]
Here is a repl of that issue: https://replit.com/@KuhlTime/LinearSdkBugReproduction#index.ts

**Comment by KuhlTime** [comment]
Was using `@linear/sdk^25` when downgrading to `^24`, it worked flawlessly. Hope that helps. 😊

**Comment by guillaumelachaud** [comment]
Fix has been released in `@linear/sdk^26`

**Comment by KuhlTime** [comment]
Thx ❤️
